### ISSUE TITLE
Build 3170

### ISSUE THREAD

**Issue by amirmasoud** [Medalink/laravel-blade#168]
Hi there,

Package not working for Sublime 3.0 Build 3170.

**Comment by nobreferreira** [comment]
It's not a problem solver, but if you disable CSS3 package you can get laravel-blade working again.

**Comment by abdolrhman** [comment]
how to remove CSS3 Completely  as , when ever i deleted it , when i restart sublime it reinstalled again .

**Comment by nobreferreira** [comment]
Why don't you simply disable the package instead of uninstall it?

**Comment by djekl** [comment]
Another issue with the latest build is the syntax highlighting. Here is an example;

Sublime 3143
![Sublime 3143](https://dha4w82d62smt.cloudfront.net/items/0t270x401H0l0B381Z0D/Image%202018-05-09%20at%207.48.45%20pm.png)

Sublime 3107
![Sublime 3107](https://dha4w82d62smt.cloudfront.net/items/1Z181L2d3Y2a1h0o3B0U/Image%202018-05-09%20at%207.49.02%20pm.png)

Same code, same packages, both have CSS3 disabled due to the issue above (disabled on old Sublime so its got the exact same packages enabled and installed)

Anyone else noticed this?

---  

Here is a snippet to re-create;

```php
$purchase_orders = collect([]);
```

```blade
@if ($purchase_orders->isEmpty())
    <div class="panel-body text-center">
        <span>No Purchase Orders Found</span>
    </div>
@else
    <table class="table table-hover" style="margin-bottom: 0;">
        <thead>
            <tr>
                <th>#</th>
                <th>Purchase Request ID</th>
                <th>Purchase Request Offer ID</th>
                <th>Customer</th>
                <th>Company</th>
                <th>Accepted By</th>
                <th>Total Price</th>
                <th>Quantity</th>
                <th>Lead Time</th>
                <th>Notes</th>
                <th>Created At</th>
                <th>Updated At</th>
            </tr>
        </thead>
    </table>
@endif
```

**Comment by djtechonline** [comment]
No longer works after last Sublime Text 3 update. Error message pops up as follows: Error loading syntax file "Packages/Laravel Blade Highlighter/blade.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
