### ISSUE TITLE
@show breaks laravel-blade

### ISSUE THREAD

**Issue by hasokeric** [Medalink/laravel-blade#40]
For some odd reason whenever i put

		<style>
		@section('styles')
		@show
		</style>

it breaks everything after it

it looks like this happens whenever the blade is inside the style tag

**Comment by ctf0** [comment]
in case anyone else was having the same problem ,this happens because the `@` is used for `@import / @keyframe / @font-face` so the blade syntax declaration will always be overridden by the browser engine ,so no solution for that but u can either

- put ur styles as inline `style="..."`
or
- stick to the old fashion css files `xxx.css`

**Comment by Medalink** [comment]
This has been fixed in 711179b7dc07824f218dee7855f38a0829672efc.
